CREATE TABLE IF NOT EXISTS CLIENT
(
    ID          IDENTITY PRIMARY KEY,
    NAME        VARCHAR(50) NOT NULL,
    CREATE_DATE TIMESTAMP   NOT NULL default CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RECORD
(
    ID          IDENTITY PRIMARY KEY,
    TITLE       VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50) NOT NULL,
    CREATE_DATE TIMESTAMP   NOT NULL default CURRENT_TIMESTAMP(),
    LAST_READ   TIMESTAMP   NULL,
    USER_ID     INT         NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES CLIENT (ID)
);

INSERT into CLIENT (NAME)
values ('client 1');

INSERT into RECORD (TITLE, DESCRIPTION, USER_ID)
values ('record 1', 'desc 1', 1),
       ('record 2', 'desc 2', 1),
       ('record 3', 'desc 3', 1);